package pickmeapp;

import javax.swing.*;
import java.awt.*;

import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.awt.GridLayout;
import java.awt.event.ActionListener; // αν χρησιμοποιείς ActionListener
import java.sql.*; // αν κάνεις χρήση βάσης δεδομένων
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import java.util.Map;
import java.util.HashMap;
import javax.swing.JList;
import javax.swing.JScrollPane;
import java.awt.BorderLayout;




public class DriverHome extends javax.swing.JFrame {

    private ImageIcon carIcon;
    private ImageIcon maleIcon;
     private JPanel requestsPanel;
    private DefaultListModel<String> listModel;
    private JList<String> requestsList;
    private Map<String, Integer> requestIdMap = new HashMap<>();
    

    
   private void sendRideRequest( int driverId ,String pickup_Address, String address) {
        String url = "jdbc:mysql://localhost:3306/pickmeapp";
        String user = "root";
        String password = "password";

        String sql = "INSERT INTO ride_requests ( driver_id, pickup_address, address) VALUES ( ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, password);
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, driverId);
            pstmt.setString(3, pickup_Address);
            pstmt.setString(2, address);
            pstmt.executeUpdate();

            System.out.println("Ride request saved!");

        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Error saving ride request.");
        }
    }
    
    public DriverHome() {
         initComponents();

        listModel = new DefaultListModel<>();
        requestsList = new JList<>(listModel);

      setTitle("Driver Home");
        setSize(366, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        

        JLabel label = new JLabel("Καλώς ήρθες οδηγέ!");
        label.setHorizontalAlignment(SwingConstants.CENTER);
        add(label, BorderLayout.NORTH);

        
        
        
        setLayout(new BorderLayout());
    

        
        
        carIcon = new ImageIcon(getClass().getResource("/pickmeapp/icons/car.png"));
        maleIcon = new ImageIcon(getClass().getResource("/pickmeapp/icons/male.png"));

        Image scaledCar = carIcon.getImage().getScaledInstance(32, 32, Image.SCALE_SMOOTH);
        Image scaledMale = maleIcon.getImage().getScaledInstance(32, 32, Image.SCALE_SMOOTH);

        carIcon = new ImageIcon(scaledCar);
        maleIcon = new ImageIcon(scaledMale);

        jToggleButton2.setIcon(maleIcon);
        
        /* requestsPanel = new JPanel();
        requestsPanel.setLayout(new BoxLayout(requestsPanel, BoxLayout.Y_AXIS));
        JScrollPane scrollPane = new JScrollPane(requestsPanel);
        scrollPane.setPreferredSize(new Dimension(350, getHeight()));
        add(scrollPane, BorderLayout.EAST);*/
        
        
        if ("DRIVER".equalsIgnoreCase(Session.pickMode)) {
    jToggleButton2.setSelected(true);
    jToggleButton2.setIcon(carIcon);
} else {
    jToggleButton2.setSelected(false);
    jToggleButton2.setIcon(maleIcon);
}
       //  loadRideRequests();
        setVisible(true);
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pickmeapp/icons/heart-938313_640.png")));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pickmeapp/icons/images.png"))); 
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pickmeapp/icons/gray-user-profile-icon-png-fP8Q1P.png"))); 
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pickmeapp/icons/Basic_Elements_(161).png"))); 
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Αναζήτηση Διαδρομής");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 36)); 
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOME");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pickmeapp/icons/notifications-1.png"))); 
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Τέλος Διαδρομής");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, 0)
                        .addComponent(jButton2)
                        .addGap(0, 0, 0)
                        .addComponent(jButton3)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(385, 385, 385)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/*     
     java.util.List<String> favoriteRoutes = Favorites.fetchFavoriteRoutesFromDB(Session.userId);

    if (favoriteRoutes.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Δεν υπάρχουν αγαπημένες διαδρομές.");
        return;
    }

    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

    for (String route : favoriteRoutes) {
        JPanel routePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        
        JLabel routeLabel = new JLabel(route);
        JToggleButton favToggle = new JToggleButton(" ♡");
        favToggle.setToolTipText("Αφαίρεση από τα αγαπημένα");

        // Έλεγχος αν είναι ήδη στα αγαπημένα
        boolean isFavorite = Favorites.checkIfFavorite(Session.userId, route);
        favToggle.setSelected(isFavorite);
        favToggle.setText(isFavorite ? "♥" : " ♡");

        favToggle.addActionListener(e -> {
            boolean selected = favToggle.isSelected();
            favToggle.setText(selected ? "♥" : " ♡");
            if (selected) {
                Favorites.addFavorite(Session.userId, route);
            } else {
                Favorites.removeFavorite(Session.userId, route);
            }
        });

        routePanel.add(routeLabel);
        routePanel.add(favToggle);
        panel.add(routePanel);
    }

    JScrollPane scrollPane = new JScrollPane(panel);
    scrollPane.setPreferredSize(new Dimension(400, 300));

    JOptionPane.showMessageDialog(this, scrollPane, "📌 Αγαπημένες Διαδρομές", JOptionPane.PLAIN_MESSAGE);*/
    Favorites.showFavorites(Session.userId);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
      
       PickModeManager.togglePickMode(this); 

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      /*   String pickup_Address = jTextField5.getText();
    String address = jTextField6.getText();

    if (pickup_Address.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Συμπλήρωσε και τις δύο διευθύνσεις.");
        return;
    }*/

    //int passengerId = Session.userId;  // Αν έχεις session
    //int driverId = Session.userId;  // Παράδειγμα – ιδανικά να είναι δυναμικό

      Route.createNewRoute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         new DriverHome(); 
         this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         new User(); 
         this.dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    loadRideRequests();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  int currentRideId = Route.getAcceptedRideRequestId(Session.userId);
    if (currentRideId == -1) {
        JOptionPane.showMessageDialog(this, "❌ Δεν υπάρχει ενεργή διαδρομή.");
        return;
    }
    Route.EndofRoute(currentRideId);
    
    String[] options = {"0", "1", "2", "3", "4", "5"};
    String ratingStr = (String) JOptionPane.showInputDialog(
        this,
        "Βαθμολόγησε τον/την συνοδοιπόρο σου (0-5):",
        "Αξιολόγηση",
        JOptionPane.PLAIN_MESSAGE,
        null,
        options,
        "5"
    );

    if (ratingStr != null) {
        int rating = Integer.parseInt(ratingStr);
        Review.saveRating(Session.userId, currentRideId, rating);
        JOptionPane.showMessageDialog(this, "✅ Η αξιολόγηση καταχωρήθηκε!");
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
   /* private void showRequestDetails(int requestId) {
    String sql = "SELECT u.name AS passenger_name, rr.address, rr.pickup_address " +
                 "FROM ride_requests rr " +
                 "JOIN users u ON rr.passenger_id = u.id " +
                 "WHERE rr.id = ?";
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pickmeapp", "root", "password");
         PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setInt(1, requestId);
        ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String passenger = rs.getString("passenger_name");
            String pickup = rs.getString("pickup_address");
            String dest = rs.getString("address");

            JOptionPane.showMessageDialog(this,
                "Επιβάτης: " + passenger + "\nΑπό: " + pickup + "\nΠρος: " + dest,
                "Λεπτομέρειες Αιτήματος", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Σφάλμα εμφάνισης λεπτομερειών: " + e.getMessage());
    }
}*/

    


    
public static void loadRideRequests() {
    String sql = "SELECT rr.id, u.id AS passenger_id, u.name AS passenger_name, rr.address, rr.pickup_address " +
                 "FROM ride_requests rr " +
                 "JOIN users u ON rr.passenger_id = u.id " +
                 "WHERE rr.driver_id = ? AND rr.status = 'PENDING'";

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pickmeapp", "root", "password");
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, Session.userId);
        ResultSet rs = stmt.executeQuery();

        JFrame requestsFrame = new JFrame("Εκκρεμή Αιτήματα Διαδρομών");
        requestsFrame.setSize(500, 600);
        requestsFrame.setLocationRelativeTo(null);
        requestsFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JPanel requestsPanel = new JPanel();
        requestsPanel.setLayout(new BoxLayout(requestsPanel, BoxLayout.Y_AXIS));

        while (rs.next()) {
            int requestId = rs.getInt("id");
            int passengerId = rs.getInt("passenger_id");
            String passengerName = rs.getString("passenger_name");
            String address = rs.getString("address");
            String pickupAddress = rs.getString("pickup_address");

            double avgRating = Review.getAverageRatingForUser(passengerId);

            JPanel requestCard = new JPanel();
            requestCard.setBorder(BorderFactory.createTitledBorder("Αίτημα"));
            requestCard.setLayout(new GridLayout(0, 1));
            requestCard.add(new JLabel("🧍 Επιβάτης: " + passengerName));
            requestCard.add(new JLabel("⭐ Μέσος Όρος Αξιολόγησης: " + (avgRating > 0 ? String.format("%.2f", avgRating) : "Δεν υπάρχουν αξιολογήσεις")));
            requestCard.add(new JLabel("📍 Διεύθυνση: " + address));
            requestCard.add(new JLabel("🚗 Επιβίβαση από: " + pickupAddress));

            JButton acceptBtn = new JButton("✅ Αποδοχή");
            JButton rejectBtn = new JButton("❌ Απόρριψη");

            acceptBtn.addActionListener(e -> {
                updateRequestStatus(requestId, "ACCEPTED");
                requestsFrame.dispose();
            });

            rejectBtn.addActionListener(e -> {
                updateRequestStatus(requestId, "REJECTED");
                requestsFrame.dispose();
            });

            JPanel buttonPanel = new JPanel();
            buttonPanel.add(acceptBtn);
            buttonPanel.add(rejectBtn);
            requestCard.add(buttonPanel);

            requestsPanel.add(requestCard);
        }

        JScrollPane scrollPane = new JScrollPane(requestsPanel);
        requestsFrame.add(scrollPane);
        requestsFrame.setVisible(true);

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "❌ Σφάλμα στη φόρτωση αιτημάτων: " + e.getMessage());
    }
}


    
     private static void updateRequestStatus(int requestId, String status) {
        String sql = "UPDATE ride_requests SET status = ? WHERE id = ?";

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pickmeapp", "root", "password");
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, status);
            stmt.setInt(2, requestId);
            stmt.executeUpdate();

         JOptionPane.showMessageDialog(null, "Η κατάσταση ενημερώθκε. "); 
         loadRideRequests();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
